### ISSUE TITLE
automate make cleanup and finishup?

### ISSUE THREAD

**Issue by gzentner** [BrendelGroup/TSRexplore#2]
I think that adding these steps to xgetstarted2 would be useful to minimize human intervention after initial setup (and the files they tidy up are accessible by simply unzipping the archive, if the user desires).

**Comment by vpbrendel** [comment]
This is true enough when all goes well, but from my own experience with these make workflows, it is easy to overlook something that did not go as planned. For example, a user might have a Makefile that asks for more memory than they actually have, and then some program early on bails out. make cleanup and finishup would still work, and superficially it looks like the workflow ran to completion.

Thus, I prefer to keep the separation, "forcing" the user to take a look at the initial output before going on to the next step.

**Comment by vpbrendel** [comment]
I have re-written the 0Record instructions to provide a path to run the entire workflow as one script. With warnings that it may be better to read the documentation ...

I call this issue closed.
