### ISSUE TITLE
Make 0Record like .xgetstarted, etc

### ISSUE THREAD

**Issue by gzentner** [BrendelGroup/TSRexplore#5]
I noted in the yeast 0Record file that everything can be copied and pasted into the terminal with the exception of resetting of rws, which is contained within an echo command:

```
#Ok, one more absolutely necessary preparatory step:
#
echo "We must set the rws variable again, as we have moved the gostripes.simg images."
echo "Execute the following (or equivalent):"
echo ""
echo "source ../GoSTRIPES/bin/xworkStripes -b `pwd` -i `pwd`/../gostripes.simg" 
echo ""
```

One option would be to make the 0Record a runnable file like the xgetstarted and other similar scripts. Alternatively, the echo for the source command line could be removed.

**Comment by vpbrendel** [comment]
I have not found such an approach to work. If you run source within a script (bash shell), then it applies to that shell. So, the setting of $rws is not available in the terminal (shell) in which you want to do the work.  Thus the approach that we have currently.  It shows the user options on how to proceed (either put a $rws permanently in their .bash profile, or define it in the working shell.
Volker

**Comment by gzentner** [comment]
That makes sense, so how about splitting the script in two, akin to xgetstarted (or it could just be 00 and 01 record). The script could stop with the echo of the source command, which would then be entered by the user as at the end of xgetstarted1, then script 2 would be the "real work," as it currently says in 0Record.

**Comment by vpbrendel** [comment]
Done. Issue closed.
